### ISSUE TITLE
Not working  as expected

### ISSUE THREAD

**Issue by senlucky** [lorenzog/burpAddCustomHeader#1]
Custom header are added to only those request which is send for spider. so i am only able to view modified requests in target tab.

Is it intentional behavior or what?

**Comment by lorenzog** [comment]
Hi,

I'm not sure what you mean really. Could you provide a bit more details? Like what are you trying to do, what happens and what did you expect?
Feel free to add a screenshot if it helps.

Thanks,

L.

**Comment by lorenzog** [comment]
Closing as no response received..
