### ISSUE TITLE
Replacing old bearer token?

### ISSUE THREAD

**Issue by drwetter** [lorenzog/burpAddCustomHeader#10]
Hi,

thanks for the extension.

The configuration seems pretty straight forward but maybe I missed something.

When I just do a automated scan with burp, I see using logger++ requests with the _Authentication: bearer_ token I supplied but  also requests with an old token I used while inspecting the application manually.

So my request  / question is: is that possible to replace **any** Authentication bearer token by the one supplied by the user?

Cheers, Dirk

PS: yes, in 'tools scope' all relevant check boxes are selected

**Comment by lorenzog** [comment]
Hello @drwetter 

Could you check whether the new update helps you with this issue please?

**Comment by drwetter** [comment]
Thanks!

I haven't checked the repeater before. For that one I can tell I it works. Not sure whether I can do an automated scan during the next few days. If so I'll let you know in any case.

**Comment by drwetter** [comment]
Seems to work, thanks! (PS: Thanks also for the plugin!)
