### ISSUE TITLE
Getting the BAppStore version updated

### ISSUE THREAD

**Issue by ngregoire** [lorenzog/burpAddCustomHeader#7]
Hi, I'm a big fan of this extension, but the current situation is messy, as the BAppStore version misses some interesting patches (extract from headers+body, avoid decoding errors for binary data), as shown in [these 2 PR](https://github.com/PortSwigger/add-custom-header/pulls).

However, to be accepted, pull requests **MUST** come from the original repository **AND** original author. This isn't the case, and that's why the BAppStore version is lagging behind.

Could you please:
- integrate the [binary decoding patch](https://github.com/PortSwigger/add-custom-header/pull/1/files)
- integrate these [mostly cosmetic changes](https://github.com/lorenzog/burpAddCustomHeader/compare/master...PortSwigger:master)
- open a PR against the portswigger version, including the changes above + the recently added ['extract from headers+body' fix](https://github.com/lorenzog/burpAddCustomHeader/commit/04536994d73253bea0623e9900792a25166d5565)

Thanks in advance!

**Comment by lorenzog** [comment]
Hi @ngregoire,

Thanks for suggesting that. I had no idea patches must come from the author - kinda defeats the whole point of collaboration, doesn't it. 
Anyhow, I've integrated the cosmetic changes and I've integrated the binary decoding patch into my repo. 
However, I can't seem to open a PR against portswigger's version. 

I'll contact portswigger to see what they can do from their end.

**Comment by ngregoire** [comment]
Thanks for the prompt feedback. Opening a PR on Portswigger repository should be doable (as already 2 people dit it).

**Comment by lorenzog** [comment]
Hi,

I really can't open a PR - I suspect it's because they forked it from mine, so they should "pull" my changes. I think it's on them now.

**Comment by ngregoire** [comment]
No idea on how to do it, but several extensions forked by Portswigger have merged PR open by their original authors:
https://github.com/PortSwigger/json-web-tokens/pulls?q=is%3Apr+is%3Aclosed
https://github.com/PortSwigger/custom-send-to/pulls?q=is%3Apr+is%3Aclosed

**Comment by Hannah-PortSwigger** [comment]
Hi Lorenzog

You should be able to open a pull request, but as you are having difficulties, we are able to merge the changes in on our end.

We haven't received an email from you yet, so if you could drop us one at support@portswigger.net then we can get started. This is so we can get in contact with you during the update process if we have any queries.

I would also like to check that the current repository is at a releasable stage.

**Comment by lorenzog** [comment]
Hi @HannahLaw-Portswigger - I did e-mail you but I've mistakenly used support@portswigger.co.uk - my bad. You should have the e-mail now.

**Comment by drwetter** [comment]
any news on this?

**Comment by lorenzog** [comment]
Hello, I thought it had been sorted by Portswigger a long time ago?

**Comment by drwetter** [comment]
Hi, me too ;-). That's why I though to speak speak up.

![burp_addheader](https://user-images.githubusercontent.com/8036727/86760486-8aab9b00-c045-11ea-8e0a-2abec3da032d.png) 

which is the date of the last commit in https://github.com/portswigger/add-custom-header

cc  @HannahLaw-Portswigger

**Comment by lorenzog** [comment]
I've pinged them also here https://github.com/PortSwigger/add-custom-header/pull/2#issuecomment-654695467 seems like the pull request is still pending

**Comment by Hannah-PortSwigger** [comment]
Hi Lorenzo

I emailed back to you on the 20th of January but cannot find a response from you to that email, which is probably why the update never went ahead.

I can put this on our BApp update and submission list, but we have a bit of a backlog at the moment, so it may still be a week or two before we can get this sorted - if it's not a big update I may be able to get it sorted a bit sooner.

Could you send us a quick email at support@portswigger.net so that I have an open ticket for this update? It can be as simple as just a link to the pull request.

**Comment by lorenzog** [comment]
Hi @HannahLaw-Portswigger - I found the e-mail, but it wasn't clear to me whether it needed a response or not - I thought all it needed was a pull request. Anyhow, I've replied now, let's hope this can be brought forward!

Thanks for the quick response as well

**Comment by lorenzog** [comment]
@drwetter the extension has been updated on the BApp store
